### ISSUE TITLE
Combined merge 2

### ISSUE THREAD

**Issue by Marko10-000** [flathub/tv.kodi.Kodi#19]
Main:
- [ ] Remove old flathub readme #15
- [ ] Remove CONTRIBUTING.md #17 
- [ ]  Add wayland support #16 
Optional:
- [ ] JSON to YAML?

**Comment by comparascope** [comment]
I pulled the text changes already. Testing yaml change now, but it looks OK to me.
